/**
 * Types for LLM-based dynamic audit question generation.
 */

/** Supported LLM provider identifiers. */
export type AuditLlmProvider = "openai" | "anthropic" | "mock";

/** Category of audit question. */
export type AuditQuestionCategory =
  | "functionality"
  | "security"
  | "robustness"
  | "performance"
  | "authorization_boundary"
  | "privilege_escalation";

/** A single structured audit question generated by the LLM. */
export interface AuditQuestion {
  /** Unique id for correlation (e.g. "q1"). */
  id: string;
  /** Category of this question. */
  category: AuditQuestionCategory;
  /** The question text to send to the agent. */
  question: string;
  /** Expected behavior description for evaluation. */
  expectedBehavior: string;
}

/** Context passed to the LLM when generating audit questions. */
export interface AuditQuestionContext {
  agentName: string;
  image: string;
  allowedHosts: readonly string[];
  allowedRpcEndpoints: readonly string[];
  /** Optional free-form description of the agent's purpose. */
  description?: string;
}

/** Configuration for the audit question generator. */
export interface AuditQuestionConfig {
  provider: AuditLlmProvider;
  apiKey: string;
  model: string;
  questionCount: number;
  /** Custom base URL for OpenAI-compatible API (e.g. "https://api.jiekou.ai/openai/v1"). */
  apiBaseUrl?: string;
  /** API format: "chat" for /chat/completions, "responses" for /responses. Default: "chat". */
  apiFormat?: "chat" | "responses";
}
