// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title ZkAuditVerifier
 * @notice Stores and verifies ZK proofs for audit score correctness and agent fingerprints.
 *
 * Two proof types:
 *   1. Audit Score Proof — proves dimensional scores were correctly computed from raw data
 *   2. Agent Fingerprint Proof — proves agent identity is bound to NFT without revealing code
 *
 * The Groth16 verifier contracts are auto-generated by snarkjs from the circom circuits.
 * This contract acts as a registry that stores proof verification results on-chain.
 */
contract ZkAuditVerifier {
    // --- Types ---

    struct AuditScoreProof {
        uint256 tokenId;
        uint256 auditId;
        uint256[6] dimensionalScores;
        uint256 overallScore;
        uint256 inputCommitment;
        bool verified;
        uint256 verifiedAt;
        bytes32 proofHash;        // keccak256 of the raw proof for dedup
    }

    struct AgentFingerprintProof {
        uint256 tokenId;
        uint256 fingerprintHash;
        uint256 developerHash;
        bool verified;
        uint256 verifiedAt;
        bytes32 proofHash;
    }

    // --- Events ---

    event AuditScoreProofVerified(
        uint256 indexed tokenId,
        uint256 indexed auditId,
        uint256 overallScore,
        uint256 inputCommitment,
        bytes32 proofHash
    );

    event AgentFingerprintProofVerified(
        uint256 indexed tokenId,
        uint256 fingerprintHash,
        uint256 developerHash,
        bytes32 proofHash
    );

    event AuditScoreVerifierUpdated(address indexed oldVerifier, address indexed newVerifier);
    event FingerprintVerifierUpdated(address indexed oldVerifier, address indexed newVerifier);

    // --- State ---

    address public owner;

    // Groth16 verifier contract addresses (set after deployment)
    address public auditScoreVerifierContract;
    address public fingerprintVerifierContract;

    // tokenId => auditId => proof record
    mapping(uint256 => mapping(uint256 => AuditScoreProof)) public auditScoreProofs;

    // tokenId => latest fingerprint proof
    mapping(uint256 => AgentFingerprintProof) public fingerprintProofs;

    // tokenId => number of verified audit proofs
    mapping(uint256 => uint256) public auditProofCount;

    // --- Modifiers ---

    modifier onlyOwner() {
        require(msg.sender == owner, "NOT_OWNER");
        _;
    }

    // --- Constructor ---

    constructor() {
        owner = msg.sender;
    }

    // --- Admin ---

    function setAuditScoreVerifier(address _verifier) external onlyOwner {
        address old = auditScoreVerifierContract;
        auditScoreVerifierContract = _verifier;
        emit AuditScoreVerifierUpdated(old, _verifier);
    }

    function setFingerprintVerifier(address _verifier) external onlyOwner {
        address old = fingerprintVerifierContract;
        fingerprintVerifierContract = _verifier;
        emit FingerprintVerifierUpdated(old, _verifier);
    }

    // --- Verify & Store: Audit Score Proof ---

    /**
     * @notice Verify a ZK proof that audit scores were correctly computed.
     * @param tokenId The agent's NFT token ID
     * @param auditId The audit ID being proven
     * @param dimensionalScores The 6 claimed dimensional scores [0-100]
     * @param overallScore The claimed weighted overall score [0-100]
     * @param inputCommitment Poseidon hash binding the proof to private inputs
     * @param proof The Groth16 proof (a, b, c points)
     */
    function verifyAuditScore(
        uint256 tokenId,
        uint256 auditId,
        uint256[6] calldata dimensionalScores,
        uint256 overallScore,
        uint256 inputCommitment,
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c
    ) external returns (bool) {
        require(auditScoreVerifierContract != address(0), "VERIFIER_NOT_SET");

        // Build public inputs array matching circuit: [dim0..5, overall, commitment]
        uint256[8] memory pubInputs;
        for (uint256 i = 0; i < 6; i++) {
            pubInputs[i] = dimensionalScores[i];
        }
        pubInputs[6] = overallScore;
        pubInputs[7] = inputCommitment;

        // Call the Groth16 verifier
        bool valid = _callGroth16Verifier(
            auditScoreVerifierContract,
            a, b, c,
            pubInputs,
            8
        );

        require(valid, "INVALID_PROOF");

        // Store the verified proof
        bytes32 proofHash = keccak256(abi.encodePacked(a[0], a[1], b[0][0], b[0][1], c[0], c[1]));

        auditScoreProofs[tokenId][auditId] = AuditScoreProof({
            tokenId: tokenId,
            auditId: auditId,
            dimensionalScores: dimensionalScores,
            overallScore: overallScore,
            inputCommitment: inputCommitment,
            verified: true,
            verifiedAt: block.timestamp,
            proofHash: proofHash
        });

        auditProofCount[tokenId] += 1;

        emit AuditScoreProofVerified(tokenId, auditId, overallScore, inputCommitment, proofHash);

        return true;
    }

    // --- Verify & Store: Agent Fingerprint Proof ---

    /**
     * @notice Verify a ZK proof binding an agent identity to its NFT.
     * @param tokenId The agent's NFT token ID
     * @param fingerprintHash The public fingerprint hash
     * @param developerHash The developer ownership hash
     * @param proof The Groth16 proof (a, b, c points)
     */
    function verifyFingerprint(
        uint256 tokenId,
        uint256 fingerprintHash,
        uint256 developerHash,
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c
    ) external returns (bool) {
        require(fingerprintVerifierContract != address(0), "VERIFIER_NOT_SET");

        // Public inputs: [fingerprintHash, tokenId, developerHash]
        uint256[3] memory pubInputs;
        pubInputs[0] = fingerprintHash;
        pubInputs[1] = tokenId;
        pubInputs[2] = developerHash;

        bool valid = _callGroth16Verifier(
            fingerprintVerifierContract,
            a, b, c,
            pubInputs,
            3
        );

        require(valid, "INVALID_PROOF");

        bytes32 proofHash = keccak256(abi.encodePacked(a[0], a[1], b[0][0], b[0][1], c[0], c[1]));

        fingerprintProofs[tokenId] = AgentFingerprintProof({
            tokenId: tokenId,
            fingerprintHash: fingerprintHash,
            developerHash: developerHash,
            verified: true,
            verifiedAt: block.timestamp,
            proofHash: proofHash
        });

        emit AgentFingerprintProofVerified(tokenId, fingerprintHash, developerHash, proofHash);

        return true;
    }

    // --- Query ---

    function getAuditScoreProof(uint256 tokenId, uint256 auditId)
        external view returns (AuditScoreProof memory)
    {
        return auditScoreProofs[tokenId][auditId];
    }

    function getFingerprintProof(uint256 tokenId)
        external view returns (AgentFingerprintProof memory)
    {
        return fingerprintProofs[tokenId];
    }

    function isAuditScoreVerified(uint256 tokenId, uint256 auditId)
        external view returns (bool)
    {
        return auditScoreProofs[tokenId][auditId].verified;
    }

    function isFingerprintVerified(uint256 tokenId)
        external view returns (bool)
    {
        return fingerprintProofs[tokenId].verified;
    }

    // --- Internal: Generic Groth16 Verifier Call ---

    function _callGroth16Verifier(
        address verifier,
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[8] memory pubInputs,
        uint256 numInputs
    ) internal view returns (bool) {
        // snarkjs-generated verifiers expose:
        //   verifyProof(uint[2] a, uint[2][2] b, uint[2] c, uint[N] input) → bool
        // We encode the call dynamically based on numInputs
        bytes memory payload;

        if (numInputs == 8) {
            payload = abi.encodeWithSignature(
                "verifyProof(uint256[2],uint256[2][2],uint256[2],uint256[8])",
                a, b, c, pubInputs
            );
        } else if (numInputs == 3) {
            uint256[3] memory inputs3;
            for (uint256 i = 0; i < 3; i++) {
                inputs3[i] = pubInputs[i];
            }
            payload = abi.encodeWithSignature(
                "verifyProof(uint256[2],uint256[2][2],uint256[2],uint256[3])",
                a, b, c, inputs3
            );
        } else {
            revert("UNSUPPORTED_INPUT_COUNT");
        }

        (bool success, bytes memory result) = verifier.staticcall(payload);
        if (!success || result.length < 32) {
            return false;
        }
        return abi.decode(result, (bool));
    }
}
